import type { Metadata } from "next";
import "@/styles/global.css";
import './govuk.scss';
import StoreProvider from "@/lib/features/store/StoreProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
   
};

export default function RootLayout({children,}:{children: React.ReactNode}) {
  return (
    <>
    <html lang="en">
      <StoreProvider>
        <body className="govuk-template ">
            {children}
        </body>
      </StoreProvider>
    </html>
  </>
  );
}
